server:
  port: 8088

path:
  local: 'D:\\img-gen\\imgs\\'
  remote: 'https://lowavl.osmiumarc.top/imgs/'


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
    url: jdbc:mysql://127.0.0.1:3306/test_db?useUnicode=true&serverTimezone=Asia/Shanghai
    password: ''
    username: root
  security:
    user:
      name: 111
      password: 123456

mybatis:
  type-aliases-package: com.micerlabs.pojo
  mapper-locations: classpath:mapper/*.xml

